# -*- coding: utf-8 -*-
"""bib1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ya8USj0Dlbq_imHQD-AKjyjp6GbVmIEA
"""



from google.colab import drive
drive.mount('/content/drive')

!ls

import os

# TODO: Change this to your Drive folder location
WORKING_DIRECTORY = '/content/drive/My Drive/Colab Notebooks'

os.chdir(WORKING_DIRECTORY)

!pip install detecto

import torch
import torchvision
import matplotlib.pyplot as plt

from torchvision import transforms
from detecto import core, utils, visualize

utils.xml_to_csv('/content/drive/MyDrive/bib1', 'bib1.csv')

# Specify a list of transformations for our dataset to apply on our images
transform_img = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize(800),
    transforms.ColorJitter(saturation=0.3),
    transforms.RandomHorizontalFlip(0.5),
    transforms.ToTensor(),
    utils.normalize_transform(),
])

dataset = core.Dataset('bib1.csv', '/content/drive/MyDrive/bib1', transform=transform_img)

loader = core.DataLoader(dataset, batch_size=5, shuffle=True)


model = core.Model(['bib'])


losses = model.fit(loader, epochs=30, verbose=True)

model.save('model_bib_large_data_low_weights.pth')

plt.plot(losses)  # Visualize loss throughout training
plt.show()

